### PR TITLE
[S3Client] Add S3_ENTPOINT_URL #8

### LINKED ISSUE #8: [Feature] Adding a S3_ENTPOINT environment variable.
Allowing the configuration of the Entpoint via this Variable allows the user to target use a AWS PrivateLink or any other S3 Compatible Storage Impementation.

This this shoud target the boto3 endpoint_url argument

### PR DESCRIPTION
**Pull request by ppvolto**
This shoud Allow to target any S3 Compatible Storage Solution or to use a AWS Private Link

Resolves #8

### CODE REVIEW

**Review by TemryL — CHANGES_REQUESTED** [review]
`S3_ENTPOINT_URL` should be `S3_ENDPOINT_URL` in `.env`and `README.md`

**Comment by TemryL** [comment]
Awesome, thanks for your contribution! Do you know what would happen if only the endpoint is given? Also, does it work with backblaze? Otherwise LGTM!

**Comment by ppvolto** [comment]
The Endpoint only says its a different host then normal every other Variable is Required. I have a private Minio Instance there i have only the problem that it creates folders in the structure `output_folder/output_folder` and the same with input but.

I never used AWS or Backblaze but any S3 Compatible implementation shoud work.

**Comment by TemryL** [comment]
Thanks!

**Pull request merged**
